### ISSUE TITLE
Does handleInactivity need to be called in componentWillMount()?

### ISSUE THREAD

**Issue by germainc** [jkomyno/react-native-user-inactivity#14]
In my current use case, I don't want onAction to fire when the component mounts.  Could we add a prop that allows that call to be skipped?  I'm guessing clearTimer and resetTimeout would have to be called instead.

Also, componentWillMount is deprecated so this should probably be moved to componentDidMount.

**Comment by jkomyno** [comment]
Hi, thank you for pointing out that `componentWillMount` is deprecated, I won't need it anymore since
I'm moving this package to hooks (#18).
At the moment, the package triggers the `onAction` property when the component mounts, which - I must admit - isn't the most intuitive behavior. So actually it would make more sense if I changed the package to prohibit triggering `onAction` at first-render time.
The new version of `react-native-user-inactivity` should be out the 13th August 2019

**Comment by jkomyno** [comment]
Hi, please check out the new version. You need to provide a custom timer to the library. In your case, just use any native background timer that works on Android too. Sorry for the delay, I just completed my bachelor's and my mind was elsewhere during these months.
