### ISSUE TITLE
Is User considered active while watching a video?

### ISSUE THREAD

**Issue by timknapp-qs** [jkomyno/react-native-user-inactivity#45]
Hi, this isn't really an issue but more of a question. I'm just wondering if a user is watching a video, does your library start counting down the timer. I have the timeout set for 20 minutes and then would log the user out. But if they are watching a 30 minute video inside my app I don't want to log them out while they are watching the video even though they have not touched the screen. Thanks!

**Comment by jkomyno** [comment]
Hi, thank you for your question. Which video component are you using? Currently `react-native-user-inactivity` relies on touch events to detect inactivity after a specific timeout. An immediate workaround would be to add a callback to your `<Video />` component that simulates a synthetic touch event every 10 seconds or so. A better solution would be to extend `react-native-user-inactivity` so that developers can send "ping" events without messing with touch events. What do you think about this?

**Comment by timknapp-qs** [comment]
@jkomyno thanks for your reply. Yes that makes sense and sounds like a good solution.
