### ISSUE TITLE
Calling setIsActive from outside?

### ISSUE THREAD

**Issue by MegazeroMZ** [jkomyno/react-native-user-inactivity#5]
So I notice that in some situation (like keyboard input and modal's input etc) the setIsActive function isnt call hence the timer dont start. So I was just wondering if you can just add the reference to the component so that we can call the setIsActive function from outside the component? Something like this:
add this to index.js
```
static propTypes = {
   ...
   onRef: PropTypes.func,
}

static defaultProps = {
   ...
   onRef: () => {},
}

componentDidMount() {
   this.props.onRef(this);
}

componentWillUnmount() {
   ...
   this.props.onRef(undefined)
}
```

And when you use the package you can do this:

```
onRef = (ref) => {
    this.userInactivity = ref;
  }

onThingsHappen = () => {
   // do something else
   // when something finish call setIsActive to start timer:
   this.userInactivity.setIsActive();
}



<UserInactivity onRef={this.onRef} ... >
</UserInactivity>
```

Something like that?

**Comment by jkomyno** [comment]
Please see my comment in #2.
Also, I don't think exposing a ref to the component would be of any utility. It would only make space for new bugs in your codebase and corrupt the state of the component itself. The real problem here is that modals and keyboard inputs aren't catched by PanResponder's API methods. Please ping me if you discover how to handle the touch events of nested TextInputs or Modal components. I'm closing this issue for now.
